time_precision: MSECS
logging_level: WARNING
reactors:
  scheduler:
    logging_level: WARNING
    message_filter:
        logging_level: WARNING
  frost_bus:
    logging_level: WARNING
    parameters:
      data_model_path: "resources/data_model/frost_bus.yml"
    message_filter:
        logging_level: WARNING
  conveyor:
    logging_level: WARNING
    parameters:
      data_model_path: "resources/data_model/conveyor.yml"
    reactors:
      message_filter:
        logging_level: WARNING
      conveyor:
        logging_level: INFO
